---
# tasks file for pan-azure-deploy
- name: Remove Subnet8
  azure_rm_subnet:
      name: "{{ tenant_subnet8 }}"
      virtual_network_name: "{{ tenant_vnet }}"
      resource_group: "{{ tenant_rg }}"
      state: absent

- name: Create subnets 
  azure_rm_subnet:
      name: "{{ item.name }}"
      virtual_network_name: "{{ item.vnet }}"
      resource_group: "{{ item.rg }}"
      address_prefix_cidr: "{{ item.prefix }}"
  with_items: "{{ subnets }}"

- name: Create Resource Group
  azure_rm_resourcegroup:
      name: "{{ vfw_rg }}"
      location: "{{ location }}"

- name: Create Storage Account
  azure_rm_storageaccount:
      resoure_group "{{ vfw_rg }}"
      name: "{{ vfw_sa }}"
      type: "{{ storage_sku }}"

- name: Deploy Firewall from Template
  azure_rm_deployment:
      state: present
      resource_group_name: "{{ vfw_rg }}"
      template_link: "./AzureDeploy.json"
      parameters:
          vmName:
              value: "{{ vpan_name }}"
